allow network synchronization to be null.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -52,10 +52,10 @@ runs:
       run: |
         set -eo pipefail
         docker run -d --name ${{ inputs.container-name }} -p ${{ inputs.ogmios-port }}:1337 -v ${{ inputs.db-dir }}:/db ${{ steps.docker-image.outputs.image }}
-        sleep 3
+        sleep 10
         URL=http://localhost:$OGMIOS_PORT/health
         echo "Begin synchronization, target: $THRESHOLD"
-        echo ""
+        echo -n ""
         for (( ;; ))
         do
           HEALTH=$(curl -sS $URL)
@@ -63,20 +63,26 @@ runs:
 
           RE='^[0-9]+\.?[0-9]*$'
           if ! [[ $NETWORK_SYNCHRONIZATION =~ $RE ]] ; then
-             echo "error: unexpected response from /health endpoint: $HEALTH"
-             exit 1
+            if [[ $HEALTH == *"\"networkSynchronization\":null"* ]]; then
+              echo -ne "\rServer isn't ready..."
+              sleep 5
+              continue
+            else
+              echo "error: unexpected response from /health endpoint: $HEALTH"
+              exit 1
+            fi
           fi
 
-          echo -e "\rnetwork synchronization: $NETWORK_SYNCHRONIZATION"
+          echo -ne "\rnetwork synchronization: $NETWORK_SYNCHRONIZATION"
           PREDICATE=$(bc <<< "$NETWORK_SYNCHRONIZATION >= $THRESHOLD")
 
           if [ "$PREDICATE" -eq 1 ]; then
+            echo "Done."
             exit 0
           else
             sleep 5
           fi
         done
-        echo -e "\rDone."
 
     - name: 🧹 Cleanup
       run: |
