Inline script in action + resolve deprecation warnings.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -37,19 +37,46 @@ runs:
       id: docker-image
       shell: bash
       run: |
-        echo "::set-output name=value::${{ inputs.repository }}:${{ inputs.version }}-${{ inputs.network }}"
+        echo "image=${{ inputs.repository }}:${{ inputs.version }}-${{ inputs.network }}" >> $GITHUB_OUTPUT
 
     - name: 📥 Pull Image
       run: |
-        docker pull ${{ steps.docker-image.outputs.value }}
+        docker pull ${{ steps.docker-image.outputs.image }}
       shell: bash
 
     - name: ⟲ Sync
+      shell: bash
+      env:
+        OGMIOS_PORT: ${{ inputs.ogmios-port }}
+        THRESHOLD: ${{ inputs.synchronization-level }}
       run: |
+        set -eo pipefail
         docker run -d --name ${{ inputs.container-name }} -p ${{ inputs.ogmios-port }}:1337 -v ${{ inputs.db-dir }}:/db ${{ steps.docker-image.outputs.value }}
         sleep 3
-        ./scripts/wait-for-sync.sh ${{ inputs.ogmios-port }} ${{ inputs.synchronization-level }}
-      shell: bash
+        URL=http://localhost:$OGMIOS_PORT/health
+        echo "Begin synchronization, target: $THRESHOLD"
+        echo ""
+        for (( ;; ))
+        do
+          HEALTH=$(curl -sS $URL)
+          NETWORK_SYNCHRONIZATION=$(sed 's/.*"networkSynchronization":\([0-9]\+\.\?[0-9]*\).*/\1/' <<< $HEALTH)
+
+          RE='^[0-9]+\.?[0-9]*$'
+          if ! [[ $NETWORK_SYNCHRONIZATION =~ $RE ]] ; then
+             echo "error: unexpected response from /health endpoint: $HEALTH"
+             exit 1
+          fi
+
+          echo -e "\rnetwork synchronization: $NETWORK_SYNCHRONIZATION"
+          PREDICATE=$(bc <<< "$NETWORK_SYNCHRONIZATION >= $THRESHOLD")
+
+          if [ "$PREDICATE" -eq 1 ]; then
+            exit 0
+          else
+            sleep 5
+          fi
+        done
+        echo -e "\rDone."
 
     - name: 🧹 Cleanup
       run: |
